payment-api:
  replicaCount: 1
  image:
    repository: haeseung/mallowlink-pay-payment-api
    tag: develop-78366f9ba6
    pullPolicy: IfNotPresent
  configmap:
    enabled: true
    values:
      SPRING_PROFILES_ACTIVE: dev
      config_host: ml-config-rollout-active-svc.ml-dev # configmap
  ingress:
    enabled: false
    className: nginx
  envFrom:
    - configMapRef:
        name: pay-test-payment-api-cm
    - secretRef:
        name: config-key-scr

  rollout:
    strategy:
      blueGreen:
        autoPromotionEnabled: true
  secrets:
    enabled: false
  otel:
    exporterEndpoint: "http://monitoring-opentelemetry-collector.logging:4317"


